# Generated by Django 5.1.2 on 2025-03-27 21:54

import main.fields
import services.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=main.fields.WebPImageField(blank=True, null=True, upload_to=services.models.get_license_image_upload_path, verbose_name='фото документа'),
        ),
    ]
