# Generated by Django 5.1.2 on 2024-11-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='prices',
            field=models.ManyToManyField(blank=True, to='prices.price', verbose_name='цены'),
        ),
    ]
