# Generated by Django 5.1.2 on 2024-11-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_information',
            field=models.TextField(blank=True, null=True, verbose_name='краткая информация'),
        ),
    ]
