# Generated by Django 5.1.2 on 2024-10-28 10:04

from django.db import migrations, models

import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_slug_servicegroup_slug_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.get_license_image_upload_path, verbose_name='фото документа'),
        ),
    ]
