services:

  dental:
    container_name: dental
    restart: always
    image: ${DOCKERHUB_USERNAME}/dental:latest
    command: >
      sh -c "cd /app/src/
      && mkdir -p media
      && uv run manage.py collectstatic --noinput
      && uv run manage.py migrate --noinput
      && uv run manage.py createsuperuser --noinput || true
      && uv run gunicorn --reload -c /app/conf/gunicorn/config.py config.wsgi:application"
    expose:
      - "8000"
    volumes:
      - static_volume:/app/src/static/
      - media_volume:/app/src/media/
    environment:
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}"
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "DEBUG=0"
      - "POSTGRES_HOST=db"
      - "POSTGRES_PORT=5432"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "YANDEX_METRIKA=${YANDEX_METRIKA}"
    depends_on:
      - db

  db:
    container_name: dental_db
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - db_volume:/var/lib/postgresql/data/

  redis:
    container_name: dental_redis
    image: redis:7-alpine
    restart: always 
    ports:
      - "6379:6379"

  nginx:
    container_name: dental_nginx
    image: ${DOCKERHUB_USERNAME}/dental-nginx:latest
    volumes:
      - static_volume:/app/src/static
      - media_volume:/app/src/media
    ports:
      - "80:80"
    depends_on:
      - dental

volumes:
  static_volume:
  media_volume:
  db_volume:
