services:

  redis:
    image: redis:7-alpine
    restart: always 
    ports:
      - "6379:6379"

  dental:
    restart: always
    build: .
    command: >
      sh -c "cd /app/src/
      && mkdir -p media
      && poetry run python manage.py collectstatic --noinput
      && poetry run python manage.py migrate --noinput
      && poetry run python manage.py createsuperuser --noinput || true
      && poetry run gunicorn --reload -c /app/conf/gunicorn/config.py config.wsgi:application"
    expose:
      - "8000"
    volumes:
      - static_volume:/app/src/static/
      - media_volume:/app/src/media/
    environment:
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}"
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "DEBUG=0"
      - "POSTGRES_HOST=db"
      - "POSTGRES_PORT=5432"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "YANDEX_METRIKA=${YANDEX_METRIKA}"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/src/static
      - media_volume:/app/src/media
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - dental

volumes:
  static_volume:
  media_volume:
