services:

  dental:
    container_name: dental
    restart: always
    build: .
    command: >
      sh -c "cd /app/src/
      && mkdir -p media
      && uv run manage.py migrate --noinput
      && uv run manage.py createsuperuser --noinput || true
      && uv run manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - "DEBUG=1"
      - "DJANGO_SUPERUSER_USERNAME=admin"
      - "DJANGO_SUPERUSER_EMAIL=admin@gmail.com"
      - "DJANGO_SUPERUSER_PASSWORD=root"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_HOST=db"
      - "POSTGRES_PORT=5432"
      - "YANDEX_METRIKA=${YANDEX_METRIKA}"
    depends_on:
      - db

  redis:
    container_name: dental_redis
    image: redis:7-alpine
    restart: always 
    ports:
      - "6379:6379"

  db:
    container_name: dental_db
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
        - dental_db_volume:/var/lib/postgresql/data/

volumes:
  dental_db_volume:
