[tool.poetry]
name = "dental-site"
version = "0.1.0"
description = ""
authors = ["MironBerch <mironberchetov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.2"
isort = "^5.13.2"
flake8 = "^7.1.1"
pep8-naming = "^0.14.1"
pillow = "^11.0.0"
django-ckeditor-5 = "0.2.15"
django-bootstrap5 = "24.3"
phonenumbers = "8.13.48"
django-phonenumber-field = "8.0.0"
django-debug-toolbar = "^4.4.6"
gunicorn = "^23.0.0"
psycopg2-binary = "^2.9.10"
django-redis = "^5.4.0"
django-cachalot = "^2.7.0"
bs4 = "^0.0.2"
beautifulsoup4 = "^4.13.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
