# Generated by Django 5.1.2 on 2025-03-27 21:54

import main.fields
import works.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=main.fields.WebPImageField(upload_to=works.models.get_staff_image_upload_path),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=main.fields.WebPImageField(blank=True, null=True, upload_to='works/previews/', verbose_name='Превью'),
        ),
    ]
