# Generated by Django 5.1.2 on 2024-12-04 16:35

import clinic.models
import django.core.validators
import django_ckeditor_5.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='о клинике')),
            ],
            options={
                'verbose_name': 'О клинике',
                'verbose_name_plural': 'О клинике',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('opening_hours', models.CharField(max_length=255, verbose_name='Часы работы')),
                ('phone_numbers', models.CharField(max_length=255, verbose_name='Номера телефонов')),
                ('email', models.EmailField(max_length=255, verbose_name='почта')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('abbreviated_name', models.CharField(max_length=255, verbose_name='Сокращенное наименование')),
                ('INN_KPP', models.CharField(max_length=255, verbose_name='ИНН/КПП')),
                ('OGRN', models.CharField(max_length=255, verbose_name='ОГРН')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(max_length=255, verbose_name='Фактический адрес')),
                ('telephone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('fax', models.CharField(max_length=255, verbose_name='факс')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
                ('website', models.CharField(max_length=255, verbose_name='Сайт')),
                ('bank_details', models.CharField(max_length=255, verbose_name='Банковские реквизиты')),
            ],
            options={
                'verbose_name': 'реквизиты',
                'verbose_name_plural': 'реквизиты',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название лицензии')),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=clinic.models.get_license_image_upload_path, verbose_name='фото документа')),
                ('pdf', models.FileField(blank=True, null=True, upload_to=clinic.models.get_license_pdf_upload_path, verbose_name='pdf файл для просмотра документа')),
                ('published', models.BooleanField(blank=True, default=True, verbose_name='является ли опубликованным')),
            ],
            options={
                'verbose_name': 'лицензия',
                'verbose_name_plural': 'лицензии',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg', models.URLField(blank=True, max_length=255, verbose_name='телеграм')),
                ('whatsapp', models.URLField(blank=True, max_length=255, verbose_name='ватсап')),
                ('vk', models.URLField(blank=True, max_length=255, verbose_name='вк')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Соглашение на обработку данных',
                'verbose_name_plural': 'Соглашения на обработку данных',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('email', models.EmailField(max_length=255, verbose_name='почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='номер телефона')),
                ('message', models.TextField(blank=True, null=True, verbose_name='сообщение')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('image', models.ImageField(blank=True, null=True, upload_to=clinic.models.get_review_image_upload_path, verbose_name='фото')),
                ('published', models.BooleanField(blank=True, default=True, verbose_name='является ли опубликованным')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
