# Generated by Django 5.1.2 on 2025-03-10 17:04

import django_ckeditor_5.fields
import phonenumber_field.modelfields

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import clinic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='о клинике')),
            ],
            options={
                'verbose_name': 'О клинике',
                'verbose_name_plural': 'О клинике',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес')),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='Часы работы')),
                ('phone_numbers', models.CharField(blank=True, max_length=255, verbose_name='Номера телефонов')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название лицензии')),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=clinic.models.get_license_image_upload_path, verbose_name='фото документа')),
                ('pdf', models.FileField(blank=True, null=True, upload_to=clinic.models.get_license_pdf_upload_path, verbose_name='pdf файл для просмотра документа')),
                ('published', models.BooleanField(blank=True, default=True, verbose_name='является ли опубликованным')),
            ],
            options={
                'verbose_name': 'лицензия',
                'verbose_name_plural': 'лицензии',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg', models.URLField(blank=True, max_length=255, verbose_name='телеграм')),
                ('whatsapp', models.URLField(blank=True, max_length=255, verbose_name='ватсап')),
                ('vk', models.URLField(blank=True, max_length=255, verbose_name='вк')),
            ],
            options={
                'verbose_name': 'Ссылки на социальные сети и контакты',
                'verbose_name_plural': 'Ссылки на социальные сети и контакты',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Соглашение на обработку данных',
                'verbose_name_plural': 'Соглашения на обработку данных',
            },
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Группа цен',
                'verbose_name_plural': 'Группы цен',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='номер телефона')),
                ('message', models.TextField(blank=True, null=True, verbose_name='сообщение')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('image', models.ImageField(blank=True, null=True, upload_to=clinic.models.get_review_image_upload_path, verbose_name='фото')),
                ('published', models.BooleanField(blank=True, default=True, verbose_name='является ли опубликованным')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=clinic.models.get_staff_image_upload_path, verbose_name='фото работника')),
                ('fio', models.CharField(max_length=100, unique=True, verbose_name='ФИО')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('information', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='информация')),
                ('roles', models.CharField(blank=True, max_length=255, verbose_name='роли или специализации')),
                ('stage', models.CharField(blank=True, choices=[('Руководитель', 'Руководитель'), ('Администратор', 'Администратор'), ('Мед персонал', 'Мед персонал'), ('Младщий мед персонал', 'Младщий мед персонал')], max_length=50, verbose_name='позиция')),
                ('published', models.BooleanField(blank=True, default=True, verbose_name='является ли опубликованным')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('cost', models.PositiveIntegerField(verbose_name='цена')),
                ('published', models.BooleanField(blank=True, default=True, verbose_name='является ли опубликованным')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.pricegroup', verbose_name='группа цен')),
            ],
            options={
                'verbose_name': 'цена',
                'verbose_name_plural': 'цены',
            },
        ),
    ]
