# Generated by Django 5.2 on 2025-05-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicegroup",
            name="short_description",
            field=models.TextField(blank=True, null=True, verbose_name="краткое описание"),
        ),
    ]
