# Generated by Django 5.1.2 on 2025-04-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='stage',
        ),
    ]
