# Generated by Django 5.1.2 on 2025-03-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='initial',
            field=models.BooleanField(default=True, verbose_name='начальная цена/окончательная'),
        ),
    ]
