# Generated by Django 5.1.2 on 2025-04-07 01:01

from django.db import migrations

import clinic.models
import main.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='image',
            field=main.fields.WebPImageField(blank=True, max_length=255, null=True, upload_to=clinic.models.get_license_image_upload_path, verbose_name='фото документа'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=main.fields.WebPImageField(blank=True, max_length=255, null=True, upload_to=clinic.models.get_staff_image_upload_path, verbose_name='фото работника'),
        ),
    ]
