# Generated by Django 5.1.2 on 2024-11-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
