# Generated by Django 5.1.2 on 2025-03-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_price_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='initial',
        ),
        migrations.AddField(
            model_name='price',
            name='constant',
            field=models.BooleanField(default=False, verbose_name='постоянная'),
        ),
    ]
