# Generated by Django 5.1.2 on 2024-10-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_about_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='published',
            field=models.BooleanField(blank=True, default=True, verbose_name='является ли опубликованным'),
        ),
    ]
