# Generated by Django 5.1.2 on 2025-01-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_contact_address_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='почта'),
        ),
    ]
