# Generated by Django 5.1.2 on 2025-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_staff_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='tg',
            field=models.URLField(blank=True, max_length=255, verbose_name='телеграм'),
        ),
        migrations.AddField(
            model_name='contact',
            name='vk',
            field=models.URLField(blank=True, max_length=255, verbose_name='вк'),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=255, verbose_name='ватсап'),
        ),
    ]
