# Generated by Django 5.1.2 on 2024-11-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_license_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg', models.URLField(max_length=255, verbose_name='телеграм')),
                ('vk', models.URLField(max_length=255, verbose_name='вк')),
                ('whatsapp', models.URLField(max_length=255, verbose_name='ватсап')),
            ],
        ),
    ]
