# Generated by Django 5.1.2 on 2025-03-27 21:54

from django.db import migrations

import clinic.models
import main.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_price_initial_price_constant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='image',
            field=main.fields.WebPImageField(blank=True, null=True, upload_to=clinic.models.get_license_image_upload_path, verbose_name='фото документа'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=main.fields.WebPImageField(blank=True, null=True, upload_to=clinic.models.get_review_image_upload_path, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=main.fields.WebPImageField(blank=True, null=True, upload_to=clinic.models.get_staff_image_upload_path, verbose_name='фото работника'),
        ),
    ]
