# Generated by Django 5.1.2 on 2025-01-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_review_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='почта'),
        ),
    ]
