# Generated by Django 5.1.2 on 2024-11-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tg',
            field=models.URLField(blank=True, max_length=255, verbose_name='телеграм'),
        ),
        migrations.AlterField(
            model_name='media',
            name='vk',
            field=models.URLField(blank=True, max_length=255, verbose_name='вк'),
        ),
        migrations.AlterField(
            model_name='media',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=255, verbose_name='ватсап'),
        ),
    ]
