# Generated by Django 5.1.2 on 2025-01-10 19:29

import phonenumber_field.modelfields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_review_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='номер телефона'),
        ),
    ]
