# Generated by Django 5.1.2 on 2025-01-28 15:04

import django_ckeditor_5.fields

from django.db import migrations, models

import clinic.models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_review_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=clinic.models.get_staff_image_upload_path, verbose_name='фото работника')),
                ('fio', models.CharField(max_length=100, unique=True, verbose_name='ФИО')),
                ('information', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='информация')),
                ('roles', models.CharField(blank=True, max_length=255, verbose_name='роли или специализации')),
                ('stage', models.CharField(blank=True, choices=[('Руководитель', 'Руководитель'), ('Администратор', 'Администратор'), ('Мед персонал', 'Мед персонал'), ('Младщий мед персонал', 'Младщий мед персонал')], max_length=50, verbose_name='позиция')),
                ('published', models.BooleanField(blank=True, default=True, verbose_name='является ли опубликованным')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
    ]
