# Generated by Django 5.1.2 on 2024-11-24 15:26

import django_ckeditor_5.fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_media_tg_alter_media_vk_alter_media_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Соглашение на обработку данных',
                'verbose_name_plural': 'Соглашения на обработку данных',
            },
        ),
    ]
