# Generated by Django 5.1.2 on 2025-03-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_staff_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
