# Generated by Django 5.1.2 on 2024-11-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='staff',
            name='roles',
            field=models.CharField(blank=True, max_length=255, verbose_name='роли или специализации'),
        ),
    ]
