# Generated by Django 5.1.2 on 2024-10-25 17:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='information',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='информация'),
        ),
    ]
